INSERT INTO cat_colonia VALUES ("08400", "CDMX", "IZTACALCO", "COL1");
INSERT INTO cat_colonia VALUES ("08400", "CDMX", "IZTACALCO", "COL2");
INSERT INTO cat_colonia VALUES ("08400", "CDMX", "IZTACALCO", "GRANJAS MEXICO");
INSERT INTO cat_colonia VALUES ("08400", "CDMX", "IZTACALCO", "COL4");

SELECT * FROM cat_colonia;